### ISSUE TITLE
NO SE VISUALIZA COMPLETA LAS BARRAS EN EL MD

### ISSUE THREAD

**Issue by naui2003** [maestria-geotel-201902/unidad-2-asignacion-1-esda-operaciones-con-atributos-plots-naui2003#1]
![image](https://user-images.githubusercontent.com/39661108/68551137-0d5d5700-03e0-11ea-9cbc-185d8e2ad341.png)

Buenas profe, genero las barras apiladas y en el R se generan bien , como la foto que le envie, pero cuando realizo el tejido, en el md se visualizan los datos cortados.

**Comment by lodurr** [comment]
@naui2003  Reduce un poco el tamaño de la letra, me paso lo mismo por que el nombre de la variable es muy largo, en vez de 12 colocale 7 o prueba con otros valores hasta que se vea como tu deseas.

**Comment by naui2003** [comment]
Ah ok lo voy hacer así. Muchas gracias Diego. Te aviso.

**Comment by lodurr** [comment]
dale, quedo atento.

**Comment by lodurr** [comment]
Si logras resolverlo, no olvides cerrar el issue 


![imagen](https://user-images.githubusercontent.com/1824882/68866059-388ac380-06ca-11ea-991c-7e0075ff544e.png)

**Comment by geofis** [comment]
Gracias @lodurr 

@naui2003, una alternativa es lo planteado por Diego, y otra sería ésta:

```
proven17 %>%
    st_drop_geometry() %>%
    dplyr::select(contains('A qué cree usted que se debe la delincuencia en su barrio o comunidad: ¿A la falta de oportunidades para estudiar?: '), TOPONIMIA) %>%
    gather(variable, valor, -TOPONIMIA) %>%
    mutate(variable=gsub('^A qué cree usted.*: ', '', variable)) %>%
    ggplot() + aes(x = TOPONIMIA, y = valor, fill = variable, group = variable) +
    geom_col(position = 'fill') + scale_y_continuous() +
    theme(axis.text.x = element_text(angle = 90), text = element_text(size = 7))  + coord_flip() +
    labs(fill = 'A qué cree usted\nque se debe la\ndelincuencia en su\nbarrio o comunidad:\n¿A la falta de\noportunidades\npara estudiar?: ')
```
